import React, { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { createFaceDetector } from '../../utils/faceDetector';
import { loadEyewearCADModel } from '../../utils/cadModelManager';
import { EyewearRig, eyewearPose, landmarkWorld } from '../../utils/landmarkEyewear';
import { generateStudioEnvironment } from '../../utils/environmentGenerator';
import { SunglassesProduct } from '../../types';
import { ProductThumbnail } from '../Catalog/ProductThumbnail';
import { ArrowLeft, Upload, Download, X, ImagePlus, Link, Glasses } from 'lucide-react';

export function PhotoTryOnPage({ products, product, onSelect, onBack }: { products: SunglassesProduct[]; product: SunglassesProduct; onSelect: (p: SunglassesProduct) => void; onBack: () => void }) {
 const [photo,setPhoto]=useState<string|null>(null), [result,setResult]=useState<string|null>(null);
 const [filename,setFilename]=useState('Your photo'), [link,setLink]=useState(''), [showLink,setShowLink]=useState(false);
 const [busy,setBusy]=useState(false), [error,setError]=useState(''), [variant,setVariant]=useState(0), [split,setSplit]=useState(50);
 const [zoom,setZoom]=useState(1), [dragging,setDragging]=useState(false), [aiBusy,setAiBusy]=useState(false);
 const request=useRef(0), urlRef=useRef<string|null>(null);
 useEffect(()=>()=>{request.current++;if(urlRef.current)URL.revokeObjectURL(urlRef.current)},[]);
 const accept=(blob:Blob,name:string)=>{if(!blob.type.startsWith('image/'))throw Error('Choose a direct JPG, PNG or WebP image.');if(blob.size>20*1024*1024)throw Error('Use an image smaller than 20 MB.');if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=URL.createObjectURL(blob);setZoom(1);setPhoto(urlRef.current);setFilename(name);setResult(null);setError('');};
 const upload=(file?:File)=>{if(!file)return;request.current++;try{accept(file,file.name)}catch(e){setError(e instanceof Error?e.message:'Image could not load')}};
 const loadLink=async(value:string)=>{const id=++request.current;setBusy(true);setError('');setResult(null);try{const url=new URL(value.trim());if(!['http:','https:'].includes(url.protocol))throw Error('Use an HTTP or HTTPS image URL.');const response=await fetch(url.href,{signal:AbortSignal.timeout(15000),credentials:'omit'});if(!response.ok)throw Error('Image link could not be opened.');const blob=await response.blob();if(id===request.current)accept(blob,'Public image');}catch(e){if(id===request.current)setError(e instanceof TypeError?'This host blocks browser access. Download the photo and upload it here.':e instanceof Error?e.message:'Image could not load');}finally{if(id===request.current)setBusy(false)}};
 useEffect(()=>{if(!photo)return;let cancelled=false;
 const run=async()=>{setBusy(true);setError('');setResult(null);let task:Awaited<ReturnType<typeof createFaceDetector>>|null=null,rig:EyewearRig|null=null,renderer:THREE.WebGLRenderer|null=null,env:THREE.WebGLRenderTarget|null=null,geometry:THREE.BufferGeometry|null=null,material:THREE.Material|null=null;
 try{const image=new Image();image.src=photo;await image.decode();if(cancelled)return;const scale=Math.min(1,4096/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.round(image.naturalWidth*scale),height=Math.round(image.naturalHeight*scale);const input=document.createElement('canvas');input.width=width;input.height=height;const ctx=input.getContext('2d');if(!ctx)throw Error('Photo processing unavailable.');ctx.drawImage(image,0,0,width,height);task=await createFaceDetector('IMAGE',2);if(cancelled)return;const analysis=document.createElement('canvas');const analysisScale=Math.min(1,1600/Math.max(width,height));analysis.width=Math.round(width*analysisScale);analysis.height=Math.round(height*analysisScale);analysis.getContext('2d')!.drawImage(input,0,0,analysis.width,analysis.height);const faces=task.detect(analysis).faceLandmarks;if(faces.length!==1)throw Error(faces.length?'Use a photo with one face.':'No face detected. Use a clear photo with both eyes visible.');const points=faces[0],pose=eyewearPose(points,width,height);if(!pose)throw Error('Could not measure this face.');const model=await loadEyewearCADModel(product,product.variants[variant]||product.variants[0]);if(cancelled)return;rig=new EyewearRig(model);renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setSize(width,height);renderer.setPixelRatio(1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;const scene=new THREE.Scene();env=generateStudioEnvironment(renderer,'studio');scene.environment=env.texture;scene.add(new THREE.HemisphereLight(0xffffff,0x716a60,1.2));const light=new THREE.DirectionalLight(0xffffff,1.5);light.position.set(-100,200,600);scene.add(light);const camera=new THREE.OrthographicCamera(-width/2,width/2,height/2,-height/2,.1,4000);camera.position.z=1000;const root=new THREE.Group();root.add(rig.group);root.position.copy(pose.position);root.quaternion.copy(pose.quaternion);root.scale.setScalar(rig.fittedScale(pose.eyeSpan,pose.faceWidth));scene.add(root);root.updateMatrixWorld(true);rig.fitTemples(root.worldToLocal(pose.leftTemple.clone()),root.worldToLocal(pose.rightTemple.clone()));const response=await fetch('/tracking/face-triangles.json');if(!response.ok)throw Error('Face surface could not load.');const triangles=await response.json();if(cancelled)return;geometry=new THREE.BufferGeometry();geometry.setIndex(triangles);geometry.setAttribute('position',new THREE.Float32BufferAttribute(points.slice(0,468).flatMap(p=>{const w=landmarkWorld(p,width,height);w.z-=pose.eyeSpan*.008;return w.toArray()}),3));material=new THREE.MeshBasicMaterial({colorWrite:false,depthWrite:true,side:THREE.DoubleSide});const mask=new THREE.Mesh(geometry,material);mask.renderOrder=-10;scene.add(mask);renderer.render(scene,camera);ctx.drawImage(renderer.domElement,0,0);if(!cancelled)setResult(input.toDataURL('image/png'));
 }catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Photo fitting failed.')}finally{task?.close();rig?.dispose();env?.dispose();geometry?.dispose();material?.dispose();renderer?.dispose();if(!cancelled)setBusy(false)}};run();return()=>{cancelled=true};},[photo,product,variant]);
 const enhance=async()=>{if(!result)return;const id=request.current;setAiBusy(true);setError('');try{const response=await fetch('/api/photo/enhance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:result}),signal:AbortSignal.timeout(180000)});const data=await response.json();if(!response.ok)throw Error(data.error||'AI enhancement failed');if(id===request.current)setResult(data.image);}catch(e){setError(e instanceof Error?e.message:'AI enhancement unavailable');}finally{setAiBusy(false)}};
 return <article className="photo-workspace">
 <button className="product-back" onClick={onBack}><ArrowLeft size={17}/> Back to fitting room</button>
 <div className="photo-workspace-heading"><span>PHOTO TRY-ON STUDIO</span><h1>Your photo. Your frames.</h1><p>Choose a portrait and a frame to create your fitted image.</p></div>
 <div className="photo-workbench"><div className="photo-inputs"><div className="photo-input-cards">
 <section className={`photo-asset-card ${dragging?'photo-drop-active':''}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);upload(e.dataTransfer.files[0])}}><header><h2>1. Face photo</h2><span>{photo?'READY':'UPLOAD'}</span></header><div className="photo-asset-preview">{photo?<><img src={photo} alt="Original face photo"/><button className="photo-remove" aria-label="Remove photo" onClick={()=>{request.current++;setPhoto(null);setResult(null);setError('');setBusy(false)}}><X size={18}/></button><span className="photo-filename">{filename}</span></>:<div className="photo-placeholder"><ImagePlus size={32}/><strong>Add your portrait</strong><span>Drag a photo here or upload below</span></div>}</div><footer><span>JPG, PNG or WebP · up to 20 MB</span><label className="photo-upload-action"><Upload size={15}/>{photo?'Replace':'Upload'}<input aria-label="Upload face photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{upload(e.target.files?.[0]);e.target.value=''}}/></label></footer></section>
 <section className="photo-asset-card"><header><h2>2. Eyewear frame</h2><span>READY</span></header><div className="photo-asset-preview photo-frame-preview"><ProductThumbnail product={product} variantIndex={variant}/><span className="photo-filename">{product.name}</span></div><footer><span>Inspect the frame · select below</span><Glasses size={17}/></footer></section>
 </div><section className="photo-settings-card"><h2>Make the look yours</h2><p>Explore the collection or bring your photo from a public image link.</p><div className="photo-setting-fields"><div><label htmlFor="photo-frame">FRAME</label><select id="photo-frame" value={product.id} onChange={e=>{request.current++;const p=products.find(p=>p.id===e.target.value);if(p){setVariant(0);onSelect(p)}}}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div><label htmlFor="photo-finish">FINISH</label><select id="photo-finish" value={variant} onChange={e=>{request.current++;setVariant(Number(e.target.value))}}>{product.variants.map((v,i)=><option key={i} value={i}>{v.name}</option>)}</select></div></div>
 <button className="photo-link-toggle" onClick={()=>setShowLink(v=>!v)} aria-expanded={showLink}><Link size={16}/> Website image link</button>{showLink&&<form className="photo-url" onSubmit={e=>{e.preventDefault();loadLink(link)}}><label htmlFor="photo-link">Direct public image URL</label><input id="photo-link" type="url" value={link} placeholder="https://example.com/face.jpg" onChange={e=>setLink(e.target.value)} onPaste={e=>{const value=e.clipboardData.getData('text').trim();if(/^https?:\/\//i.test(value)){e.preventDefault();setLink(value);loadLink(value)}}} required/><button className="photo-primary" disabled={busy}>Load image & fit frames</button></form>}<p className="photo-privacy">Fitting runs on your device. AI enhance sends the fitted image to OpenAI only when clicked. Image links must allow browser access.</p>{error&&<p className="photo-error" role="alert">{error}</p>}</section></div>
 <section className="photo-result-card" aria-live="polite"><div className={`photo-result-stage ${zoom>1?'photo-result-zoomed':''}`}><div className="photo-zoom-content" style={{width:`${zoom*100}%`,height:`${zoom*100}%`,position:'relative'}}><div className="photo-result-labels"><span>ORIGINAL</span><span>{result?'FITTED RESULT':'PREVIEW'}</span></div>{photo?<><img className="photo-result-image" src={result||photo} alt={result?`${product.name} fitted on your face`:'Photo preview'}/>{result&&<><img className="photo-result-original" src={photo} alt="Original for comparison" style={{clipPath:`inset(0 ${100-split}% 0 0)`}}/><div className="photo-split-line" style={{left:`${split}%`}}><span>↔</span></div><input className="photo-split-control" type="range" min="0" max="100" value={split} onChange={e=>setSplit(Number(e.target.value))} aria-label="Compare original and fitted image"/></>}</>:<div className="photo-result-empty"><Glasses size={40}/><h2>Your next look starts here</h2><p>Upload a face photo to see your fitted result.</p></div>}</div>{(busy||aiBusy)&&<div className="photo-rendering" role="status"><span/>{aiBusy?'AI enhancement in progress…':'Analyzing & fitting your frames…'}</div>}</div><div className="photo-result-tools"><button onClick={()=>setZoom(z=>Math.max(1,z-.5))} aria-label="Zoom out">−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(4,z+.5))} aria-label="Zoom in">+</button><button onClick={()=>setZoom(1)}>Fit</button><button disabled={!result||busy||aiBusy} onClick={enhance}>AI enhance</button></div><footer><span className={result&&!busy?'photo-result-ready':''}>● {busy?'PROCESSING':result?'RENDER READY · PNG':'WAITING FOR PHOTO'}</span>{result&&!busy&&<a className="photo-download" href={result} download={`lumen-${product.id}.png`}><Download size={15}/> Download</a>}</footer></section>
 </div></article>;
}
