import { writeFileSync } from 'node:fs';
import { SUNGLASSES_CATALOG } from '../src/data/catalog.js';

// Bundle the catalog into the function: browser-only module resolution must
// not be required when Vercel invokes the Node handler.
writeFileSync('api/products.ts', `// Generated by scripts/generateCatalogAPI.ts during build.\nconst products = ${JSON.stringify(SUNGLASSES_CATALOG)};\nexport default function handler(_req: unknown, res: { status(code: number): { json(value: unknown): void } }) {\n  res.status(200).json({ success: true, data: products });\n}\n`);
